spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/study?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: "!qkr0147258"
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug