spring:
  h2:
    console:
      enabled: true # h2 콘솔 사용
      path: /h2   # localhost:port/h2 로 접근 가능
      settings:
        trace: false  # Print additional trace information
        web-allow-others: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500

logging:
  level:
    org.hibernate.SQL: debug